migration_mode: true

log:
  level: debug

postgres:
  dsn: postgres://postgres:password@127.0.0.1:5432/vilingvum?sslmode=disable
  log_level: "debug"

server:
  addr: ":8080"

  limiter:
    max_requests: 100
    expiration: 1m

  cache:
    expiration: 1h

bot:
  token: "token"