version: '3.8'

services:
  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: vilingvum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
