-- DROP SCHEMA IF EXISTS public CASCADE;


DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS invite_codes CASCADE;
DROP TABLE IF EXISTS post_entries CASCADE;

