-- DROP SCHEMA IF EXISTS public CASCADE;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS user_answers CASCADE;
DROP TABLE IF EXISTS dictionary CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;

DROP EXTENSION "uuid-ossp";